apiVersion: v1
kind: Pod

metadata:
  name: empty-dir-demo
  namespace: default

spec:
  containers:
  - name: nginx
    image: nginx
    
# mounting the volume to nginx 
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs

# mounting the volume to almalinux
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]

    volumeMounts:
    - mountPath: /mnt/nginx-log
      name: nginx-logs
      readOnly: true # if we mention readOnly true almalinux cannot modify amything it just read the logs 

# creating volumes with name nginx-logs
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 100Mi
