# creating pv is k8 admin job 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-estatic
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclainPolicy: Retain # retain means dont delete data,recycle means delete data dont delete disk,delete means delete the disk
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-000a16421872c7615
 